### ISSUE TITLE
Permitir que um cliente tenha não apenas uma, mas várias contas

### ISSUE THREAD

**Issue by StanleySathler** [stanley-java-projects/aprendendo-git-com-java#1]
Atualmente um `Cliente` só pode ter apenas uma `Conta`. Já que um cliente, em tese, pode possuir várias contas diferentes, deveríamos permitir essa opção.

Para solucionar este problema, podemos alterar a propriedade `Conta conta` da classe `Cliente` para algo como `ArrayList<Conta> contas`. Dessa forma teríamos não apenas uma conta, mas uma lista de contas.

**Comment by MarcosHGA** [comment]
Issue resolvida pelo commit abaixo:
https://github.com/stanley-java-projects/aprendendo-git-com-java/commit/1b05c857c73ba56805f68892a1c9f3796a8aaba0
