### ISSUE TITLE
Adicionar saldo às contas

### ISSUE THREAD

**Issue by StanleySathler** [stanley-java-projects/aprendendo-git-com-java#2]
Contas bancárias possuem saldos. Portanto, a classe `Conta` deveria ter uma propriedade `saldo` do tipo `double`:

```Java
public class Conta {
    private double saldo;
    /* Restante do código */
}
```

A classe também deve conter dois métodos adicionais: `Conta#saca()` e `Conta#deposita()`. Ambos os métodos **não precisam** fazer nenhuma checagem em relação à limite ou saldo atual da conta (ou seja, permite depositar ou sacar quanto quiser).

**Comment by PauloEF** [comment]
Corrigido no commit https://github.com/stanley-java-projects/aprendendo-git-com-java/commit/aebd037b5ed1379594f88e4ff7a935382e330d67
